#!/usr/bin/env python3
"""Generate paper tables into paper/tables/*.tex.

Each table is one function registered in TABLES. It should return a LaTeX
string (use booktabs: \\toprule/\\midrule/\\bottomrule). Output is written to
<outdir>/<name>.tex and \\input{} from the paper.

Usage:
    python analysis/make_tables.py --outdir paper/tables
    python analysis/make_tables.py --outdir paper/tables --only table1_benchmark
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Callable

TABLES: dict[str, Callable[[], str]] = {}


def table(name: str):
    """Register a table builder under `name` (-> <outdir>/<name>.tex)."""

    def deco(fn: Callable[[], str]):
        TABLES[name] = fn
        return fn

    return deco


# --------------------------------------------------------------------------
# Table builders. Placeholder until the 10-mammal RiNALMo run is summarized.
# --------------------------------------------------------------------------


@table("table1_benchmark")
def _table1() -> str:
    rows = [
        # (genome_pair, short_ncRNA_recovered, lncRNA_islands_aligned)
        ("human--mouse", "--", "--"),
    ]
    body = " \\\\\n    ".join(f"{a} & {b} & {c}" for a, b, c in rows)
    return (
        "% Auto-generated by analysis/make_tables.py -- do not edit by hand.\n"
        "\\begin{table}[t]\n"
        "  \\centering\n"
        "  \\caption{Benchmark summary.}\n"
        "  \\label{tab:benchmark}\n"
        "  \\begin{tabular}{lrr}\n"
        "    \\toprule\n"
        "    Genome pair & Short ncRNA recovered & lncRNA islands aligned \\\\\n"
        "    \\midrule\n"
        f"    {body} \\\\\n"
        "    \\bottomrule\n"
        "  \\end{tabular}\n"
        "\\end{table}\n"
    )


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--outdir", type=Path, default=Path("paper/tables"))
    p.add_argument("--only", nargs="*", help="only build these table names")
    args = p.parse_args()

    args.outdir.mkdir(parents=True, exist_ok=True)
    names = args.only or list(TABLES)
    for name in names:
        if name not in TABLES:
            raise SystemExit(f"unknown table: {name} (have: {', '.join(TABLES)})")
        out = args.outdir / f"{name}.tex"
        out.write_text(TABLES[name]())
        print(f"wrote {out}")


if __name__ == "__main__":
    main()
